### PR TITLE
Issue 17 create load generator boilerplate

### PR DESCRIPTION
**Pull request by holzeis**
- [x] Setup simple http server based on spring boot (kotlin)
 - [x] Create aca-py callback api skeleton
 - [x] Create load test api skeleton
 - [x] Create Dockerfile

### CODE REVIEW

**Review by geahaad — COMMENTED** [review]
Please merge https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore into `.gitignore` and rebase (i.e. remove `.idea/libraries/...`)

**Comment by geahaad** [comment]
> Please merge https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore into `.gitignore` and rebase (i.e. remove `.idea/libraries/...`)

Never mind - my bad.
Weird... I see `.idea/**/libraries` is already excluded, but why are files such as `.idea/libraries/maven*` under version control?

**Comment by holzeis** [comment]
> > Please merge https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore into `.gitignore` and rebase (i.e. remove `.idea/libraries/...`)
> 
> Never mind - my bad. Weird... I see `.idea/**/libraries` is already excluded, but why are files such as `.idea/libraries/maven*` under version control?

I've used https://www.toptal.com/developers/gitignore to generate the gitignore for kotlin, maven and intellij.

**Comment by geahaad** [comment]
> https://www.toptal.com/developers/gitignore

https://gitignore.io --> awesome tip. Thanks!

Boilerplate builds & runs on my machine! Approved!

**Review by geahaad — APPROVED** [review]

**Pull request merged**
