### PR TITLE
Implement Postgres Cluster for wallet DB

### PR DESCRIPTION
**Pull request by iliecirciumaru**

### CODE REVIEW

**Comment by PaulWen** [comment]
Do we need to update the Postgres Monitoring and Dashboard setup too?

**Comment by geahaad** [comment]
Battling with container networking issues on Linux. Seems that the agents on `aries-load-test` can ot resolve the nodes on `von` anymore.

**Comment by iliecirciumaru** [comment]
@PaulWen @geahaad I resolved merge conflicts

**Comment by iliecirciumaru** [comment]
> Do we need to update the Postgres Monitoring and Dashboard setup too?

Yes, but I don't really know how to do it

**Review by PaulWen — APPROVED** [review]

**Pull request merged**
